server:
  port: 8082

service:
  communal:
    uri: http://localhost:8081
    path:
      communal-service: /communal/account/all
      communal-debtors: /communal/account/debtors
    audience: communal-service

#Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/communals
    username: account
    password: account
  liquibase:
    change-log: classpath:db/init.xml
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: yDghlyvw2nTb6DTCzYnx6Z66PNNP918t
            client-secret: frYCqnXPXL5s1-7R3FVpE8ZTdtO0MVMCwPLUCkt4twZnW8QFUHEqXzEFkFMSNr5a
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-6479d9ck.us.auth0.com/