#Spring Boot Hibernate
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/communals
    username: account
    password: account
  jpa:
    show-sql: true
  liquibase:
#    change-log: classpath:db/init.xml
    change-log: classpath:db/insert_values.xml

tariffs:
  const:
    houseMaintenatce:
    currentRepair:
    garbageRemove:
    elevatorMaintenance:
  variable:
    electricity:
    coldWater:
    hotWater: