
###
GET http://localhost:8080/communal/account/all
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==

###
GET http://localhost:8080/communal/account/3
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==

###
GET http://localhost:8080/communal/service_type/all
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==

###
GET http://localhost:8080/communal/service_type/2
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==

###
POST http://localhost:8080/communal/service_type/update_tariff
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==
Content-Type: application/json

{
    "id": 2,
    "tariff": 23.00
}

###
POST http://localhost:8080/communal/payment
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==
Content-Type: application/json

{
  "accountId": 1,
  "serviceId": 5,
  "sum": 200.50
}

###
GET http://localhost:8080/communal/account/debtors
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==
#Authorization: Basic a2lzc2tldHM6aWxvbmdyb3Nz

###
POST http://localhost:8080/communal/auth/create_user
Authorization: Basic aWxvbmdyb3NzOmlsb25ncm9zcw==
#Authorization: Basic YmVlem9zczoxMjM0NQ==
Content-Type: application/json

{
  "login": "beezoss",
  "password": "12345"
}